import React from "react";
import PageTemplate from "./PageTemplate";
import { Typography } from "@mui/material";

const TermsAndConditions = () => {
  return (
    <PageTemplate title="Terms and Conditions">
      <Typography
        variant="body1"
        paragraph
        fontFamily="Bricolage Grotesque"
        fontSize={16}
      >
        These terms and conditions (“User Terms”) apply to the User (“Your,
        You”) who visit and use the Site whether through a computer or a mobile
        phone, the Service and the Application, as well as to all information,
        recommendations and or services provided to You on or through the Site,
        and the Application. This document is an electronic record in terms of
        Information Technology Act, 2000 and rules thereunder as applicable and
        the provisions pertaining to electronic records in various statutes as
        amended by the Information Technology Act, 2000. <br></br>
        <br></br>
        This electronic recordis generated by a computer system and does not
        require any physical or digital signatures. <br></br>
        <br></br> By clicking on the “I ACCEPT” button or by using InLane’s
        services, You are acknowledging and consenting to be bound by these User
        Terms. <br></br>
        <br></br> PLEASE ENSURE THAT YOU READ AND UNDERSTAND ALL THESE USER
        TERMS BEFORE YOU USE THE SITE.<br></br>
        <br></br> If You do not wish to accept any of the User Terms, then
        please do not use the Site or avail any of the services being provided
        therein.<br></br>
        <br></br> YOUR AGREEMENT TO THESE USER TERMS SHALL OPERATE AS A BINDING
        AGREEMENT BETWEEN YOU AND INLANE IN RESPECT OF THE USE AND SERVICES OF
        THE SITE. <br></br>
        <br></br>Your access and use of the Services constitutes your agreement
        to be bound by these Terms, which establishes a contractual relationship
        between you and INLANE. These Terms expressly supersede prior agreements
        or arrangements with you. INLANE may immediately terminate these Terms
        or any Services with respect to you, or generally cease offering or deny
        access to the Services or any portion thereof, at any time for any
        reason. Supplemental terms may apply to certain Services, such as
        policies for a particular event, activity or promotion, and such
        supplemental terms will be disclosed to you in connection with the
        applicable Services. Supplemental terms are in addition to, and shall be
        deemed a part of, the Terms for the purposes of the applicable Services.
        Your acceptance of the User Terms shall be deemed to include your
        acceptance of the privacy policy available at{" "}
        <a href="/privacy-policy">link</a> . By accepting these User Terms, You
        also allow InLane to send you promotional emails and SMS alerts from
        time to time.
        <br></br>
        <br></br>IT IS HEREBY EXPRESSLY CLARIFIED THAT THESE USER TERMS WILL NOT
        APPLY TO CORPORATE ENTITIES WHO ARE GOVERNED BY THE INLANE CORPORATE
        TERMS OF USE. HOWEVER, ALL AUTHORIZED USERS TAKING ‘INLANE CORPORATE
        LESSONS’ I.E., FOR CUSTOMERS WHO ARE AVAILING LESSONS UNDER THE DIRECT
        ARRANGEMENTS BETWEEN CORPORATE ENTITIES AND INLANE SHALL ALSO BE
        GOVERNED BY THESE USER TERMS.
      </Typography>
      <Typography
        variant="body1"
        paragraph
        fontFamily="Bricolage Grotesque"
        fontSize={16}
      >
        1. DEFINITIONS <br></br>
        All of the defined and capitalized terms in these User Terms will have
        the meaning assigned to them here below:<br></br>
        (i) “Account” shall mean the account created by the Learner on the
        Platform for availing the Services provided by InLane.<br></br>
        (ii) “Additional Fee” shall mean any taxes or platform fee that may have
        been incurred in providing the Services and payable to any third party /
        government authorities for undertaking the Lesson under Applicable Law.
        <br></br>
        (iii) “Applicable Laws” shall mean and include all applicable statutes,
        enactments, acts of legislature or parliament, laws, ordinances, rules,
        by-laws, regulations, notifications, guidelines, policies, directions,
        directives and orders of any governmental authority, tribunal, or a
        court of India.<br></br>
        (iv) “Platform” shall mean the mobile application and website updated by
        InLane from time to time.<br></br>
        (v) “Convenience Fee”/” Access Fee” shall mean the fee payable by the
        Customer to InLane for the Service i.e., for availing value-added
        services including but not limited to technology services, door to door
        service, customer support and cashless payment options. <br></br>
        (vi) “Reschedule Fee” shall mean a fee payable by You, towards
        rescheduling of a lesson
        <br></br>(vii) “City of Operation” shall mean a city in which the
        learners and Driving Instructors avail and render the transportation
        services respectively. For clarity, the services rendered by the Driving
        Instructors and availed by the Customers shall be in the same city.
        <br></br>
        (viii) “Learner/ You” means a person who has an Account on the Platform.
        <br></br>
        (ix) “Driving Instructor” shall mean and include such individuals as may
        be evaluated, appointed and trained by an operator associated with us to
        provide the instruction services and persons who are registered with
        InLane and own such Vehicles with necessary permits and other applicable
        transport vehicle permits and licenses to provide transportation
        services within the City of Operation.<br></br>
        (x) “E-Wallet” shall mean a pre-paid instrument, which can be used to
        make payments. <br></br>
        (xi) “Fees” shall mean such amount payable by You in Indian Rupees,
        which is reflected on the Application, as the fees payable towards the
        lesson. Fees may depend on several factors such as the availability of
        the Driving Instructor(s) on the platform at the time, city and may also
        reflect the Fees that may have been stipulated by the respective
        Governments from time to time. It may include components to reflect any
        promotions carried out by InLane.<br></br>
        (xii) “Force Majeure Event” shall mean any event arising due to any
        cause beyond the reasonable control of InLane.<br></br>
        (xiii) “InLane” or “us” or “we” or “our” shall mean InLane Technologies
        Private Limited, a company incorporated under the provisions of the
        Companies Act, 1956 and having its registered office at 3rd floor,
        Akruti Chambers, Stage 2, Hoysala Nagar, Indiranagar, Bengaluru,
        Karnataka 560038, which expression shall, unless it be repugnant to the
        context or meaning thereof, be deemed to mean and include all its
        successors, affiliates and permitted assigns.<br></br>
        (xiv) “Registration Data” shall mean and may include the present, valid,
        true and accurate name, email ID, phone number and such other
        information as may be required by InLane from the Customer from time to
        time for registration on the Application. (xv) “Lesson” shall mean the
        instruction duration in the Vehicle by the Learner facilitated through
        the Site.<br></br>
        (xvi) “Service(s)” means the facilitation of the services by InLane
        through the Application or via booking on the Site.<br></br>
        (xvii) “Site” shall mean the Application and the website (www.inlane.in)
        operated by InLane or any other software that enables the use of the
        Application or such other URL as may be specifically provided by InLane.
        <br></br>
        (xviii) “Total Lesson Fee” may comprise one or more of the following
        components that shall be levied to the Lesson based on various
        parameters including but not limited to the duration of the Lesson, city
        in which the Lesson is hailed, time of the day, availability of Driving
        Instructors nearby.<br></br>
        (ix) “T&Cs” and “User Terms” shall mean these Customer terms and
        conditions.<br></br>
        (x) “TPSP” shall mean a third-party service provider.<br></br>
        (xi) “Vehicle” shall mean a motor cars and two wheelers as defined under
        the Motor Vehicles Act,1988.<br></br>
        <br></br>
        2. ELIGIBILITY
        <br></br>
        You will be “Eligible” to use the Services only when You fulfil all of
        the following conditions:<br></br>
        (i) You have attained at least 18 (eighteen) years of age for learning a
        four-wheeler motor car. <br></br>
        (ii) You are competent to enter into a contract under the Applicable
        Laws. <br></br>
        (iii) You have attained at least 16 (sixteen) years of age for learning
        a two-wheeler.
        <br></br>
        If You reside in a jurisdiction that restricts the use of the Service
        because of age or restricts the ability to enter into contracts such as
        this User Terms due to age, You must abide by such age limits.<br></br>
        <br></br>
        3. REGISTRATION AND ACCOUNT
        <br></br>
        3.1 You understand and acknowledge that You can register on the Site
        only after complying with the requirements of this Clause 3 and by
        entering Your Registration Data.<br></br> 3.2 You shall ensure that the
        Registration Data provided by You is accurate, complete, valid, true and
        is updated from time to time. We shall bear no liability for false,
        incomplete, old or incorrect Registration Data provided by You.<br></br>{" "}
        3.3 You are solely responsible for maintaining the confidentiality of
        Your Registration Data and will be liable for all activities and
        transactions that occur through Your Account, whether initiated by You
        or any third party. Your Account cannot be transferred, assigned or sold
        to a third party. We shall not be liable for any loss that You may incur
        as a result of someone else using Your password or Account, either with
        or without Your knowledge.<br></br> 3.4 We reserve the right to suspend
        or terminate Your Account with immediate effect and for an indefinite
        period, if We have a reason to believe that the Registration Data or any
        other data provided by You is incorrect or false, or that the security
        of Your Account has been compromised in any way, or for any other reason
        We may find just or equitable.<br></br> 3.5 Except for the Registration
        Data or any other data submitted by You during the use of any other
        service offered through Site (“Permitted Information”), InLane does not
        want You to, and You should not, send any confidential or proprietary
        information to InLane on the Site or otherwise, unless otherwise is
        required by Applicable Laws. In accepting these User Terms, You agree
        that any information or materials that You or individuals acting on Your
        behalf provide to InLane other than the Permitted Information will not
        be considered confidential or proprietary.<br></br> 3.6 It is Your
        responsibility to check to ensure that You download the correct
        application for Your device. We are not liable if You do not have a
        compatible mobile device or if You download the wrong version of the
        Application for Your mobile device. We reserve the right to terminate
        the Service, and the use of the Application should You be using the
        Service or Application with an incompatible or unauthorized device.
        <br></br> 3.7 You agree to comply with all applicable laws when using
        the Services, and you may only use the Services for lawful purposes
        (e.g., no transport of unlawful or hazardous materials). You will not,
        in your use of the Services, cause nuisance, annoyance, inconvenience,
        or property damage, whether to the Third-Party Provider or any other
        party. In certain instances, you may be asked to provide proof of
        identity to access or use the Services, and you agree that you may be
        denied access to or use of the Services if you refuse to provide proof
        of identity. The proof of identity will encompass, but is not limited
        to, ensuring that the Driving Instructor verifies the Learner's identity
        by matching their photograph on our platform with the individual
        arriving for the lesson.<br></br> 3.8 We allow You to open only one
        Account in association with the Registration Data provided by You. In
        case of any unauthorized use of Your Account please immediately reach Us
        at (Contact).<br></br> 3.9 In case, You are unable to access Your
        Account, please inform Us at (Contact) and make a written request for
        blocking Your Account. We will not be liable for any unauthorised
        transactions made through Your Account prior to the expiry of 72
        (seventy-two) hours after You have made a request in writing for
        blocking Your Account and shall not have any liability in case of Force
        Majeure Event.<br></br>
        <br></br>
        4. SERVICES
        <br></br>
        The Services constitute a technology platform that enables users of
        INLANE’s mobile applications or websites provided as part of the
        Services (each, an “Application”) to act as an online platform
        connecting driving instructors with learners as service.<br></br> 4.1.
        The Services allows You to send a request through InLane to a Driving
        Instructor registered as an instructor on the InLane network. If the
        Driving Instructor accepts a request based on their availability, InLane
        notifies You and provides information regarding the Driving Instructor-
        including Driving Instructor name, Vehicle license number, telephone
        contact details of the Driving Instructor and such other details as
        InLane may determine.<br></br> 4.2. InLane shall procure reasonable
        efforts to bring You into contact with a driving instructor, subject to
        the availability of Driving Instructor in or around Your location at the
        moment of Your request for such services.<br></br> 4.3. By using the
        Application or the Service, You further agree that: (i) You will only
        use the Service or download the Application for Your sole, personal use
        and will not resell or assign it to a third party; (ii) You will not use
        an account that is subject to any rights of a person other than You
        without appropriate authorization; (iii) You will not use the Service or
        Site for unlawful purposes; (iv) You will not try to harm the Service,
        Site or our network in any way whatsoever; (v) You will provide InLane
        with such information and documents which InLane may reasonably request;
        (vi) You will only use an authorized network to avail the Service; (vii)
        You are aware that when requesting Services, whether by message, via
        Site or Application of InLane, standard messaging charges, data charges,
        voice charges, as applicable, of the Your and Our phone network service
        providers, will apply; (viii) You will comply with all Applicable Law
        from Your country of domicile and residence and the country, state
        and/or city in which You are present while using the Site or Service;
        and (ix) You are aware of and shall comply with the Information
        Technology Act, 2000 and the rules, regulations and guidelines notified
        thereunder.<br></br> 4.4. InLane reserves the right to immediately
        terminate the Service and the use of the Application in the event of
        non-compliance with any of the above requirements. Further, InLane will
        store the information provided by You or record your calls for
        contacting You for all Service-related matters. You shall promptly
        inform InLane on any change in the information provided by You.<br></br>{" "}
        4.5. InLane or an authorized representative of InLane, shall provide
        information regarding services, discounts and promotions provided by
        InLane or a TPSP to You on the InLane App or by way of an SMS or email
        to Your registered mobile number/registered email ID. You also have the
        option to discontinue receiving such information at any point of time.
        To discontinue receiving such information, You may at any point of time
        visit the specific link provided in the Site to discontinue the same.
        <br></br>
        4.6. You agree to grant InLane a non-exclusive, worldwide, perpetual,
        irrevocable, royalty free, sub-licensable (through multiple tiers) right
        to exercise the copyright, publicity, database rights or any other
        rights You have in your information, in any media now known or not
        currently known, with respect to Your information. YOU AGREE AND PERMIT
        INLANE TO SHARE YOUR INFORMATION AND/OR PERMITTED INFORMATION, WITH
        THIRD PARTIES.<br></br> 4.7. You agree and permit InLane to share any
        information provided by You with third parties in order to facilitate
        provision of certain value-added services offered by such third parties
        to You and/or to provide certain value-added services to You by InLane.
        You hereby expressly consent to receive communications from InLane/
        third parties offering value-added services to You through Your
        registered phone number and/or e-mail id and/or the Site. You agree that
        You will not hold InLane responsible for any such communications
        received from third parties, nor will any such communication amount to
        spam, unsolicited communication or a violation of Your registration on
        the national do not call registry.<br></br> 4.8. InLane will be entitled
        to enter into any tie-up in terms of joint-venture or otherwise with any
        other institution engaged in the business of providing services
        analogous and/or similar to those herein contained. In such case,
        depending upon the modality and the mechanism as may be devised, You
        will be provided with the services by InLane jointly and/or severally
        with the party/ies in joint venture. You hereby give Your irrevocable
        consent and permission to such a tie-up. In the event of such a tie-up,
        the terms and conditions herein contained will, mutatis mutandis, become
        applicable in respect of such tie-up arrangement also.<br></br> 4.9. In
        the event of breakdown of the Vehicle, which is beyond repair, before
        completion of the Lesson, InLane on a best effort basis and at its sole
        discretion may arrange for a Substitute Vehicle for completion of Your
        Lesson to Your destination. However, the arrangement of Substitute
        Vehicle shall be subject to its availability.<br></br> 4.10. You
        acknowledge and agree that Substitute Vehicle may not be necessarily of
        the same type as the original Vehicle booked by You from the Site.
        <br></br> 4.11. InLane bears no responsibility and liability for delays
        and losses suffered by You or caused to You as a consequence of the
        breakdown of the Vehicle or the Substitute Vehicle.
        <br></br>
        <br></br>
        5. CONFIRMATION OF BOOKING
        <br></br>
        5.1. InLane shall, upon receiving the booking request from You in the
        manner set out above, proceed to confirm or decline the booking based on
        the availability of Vehicles at the pickup time and location , which
        shall be informed to You via the Platform or SMS or email. In the event
        the booking is confirmed, You shall check the booking details including
        but not limited to pick up time and pick up place, and if there is
        incorrect detail, the same needs to be informed to us immediately by
        calling our call center.<br></br> 5.2. Upon confirmation of booking, a
        One Time Pin (OTP) shall be provided on the Application which shall be
        further shared by the Customer with the Driving Instructor. In the event
        that the Customer does not provide OTP to the Driving Instructor,
        Driving Instructor shall not be responsible for not starting on the
        services.<br></br> 5.3. You shall bear the consequences and damages for
        any delay that may be caused to You due to Your failure to check the
        confirmation message via the application, SMS or email or failure to
        inform InLane of the incorrect details immediately.<br></br> 5.4. All
        Lessons provided under this agreement are exclusively for the use of the
        registered Learner. Under no circumstances may a registered Learner
        transfer their lessons to another individual or existing Learner. Each
        Lesson is non-transferable and may only be utilized by the person for
        whom it was originally registered. Any attempt to transfer lessons or
        associated benefits to another party will be considered a breach of this
        agreement and may result in the forfeiture of the lessons and any
        associated credits.
        <br></br>
        <br></br>
        6. PAYMENT
        <br></br>
        Please refer to our Payment Policy at{" "}
        <a
          href="/payment-policy"
          style={{ color: "#1976d2", textDecoration: "underline" }}
        >
          link
        </a>
        <br></br>
        <br></br>
        7. REFUNDS AND CANCELLATIONS
        <br></br>
        7.1. Cooling-Off Period: If You change Your mind after purchasing a
        package, You may request a full refund within 24 (twenty-four) hours of
        payment, provided no lessons have been scheduled or conducted.<br></br>{" "}
        7.2. Unused Lessons: Where more than 80% of Your lessons remain unused,
        a refund will be issued for the unused portion, less a processing fee of
        INR 2,500. Where 80% or fewer lessons remain, refunds are not applicable
        except in cases of Special Circumstances or a Force Majeure Event as set
        out in the Refund Policy.<br></br> 7.3. Cancellations: Lessons cancelled
        with 24 (twenty-four) hours' or more notice are returned to Your account
        as a credit at no penalty. Lessons cancelled with less than 24
        (twenty-four) hours' notice may be forfeited. Lessons cancelled by
        InLane or the Driving Instructor will be rescheduled at no cost or
        credited back to Your account, at Your preference.<br></br> 7.4.
        Non-Refundable Items: Administrative and registration fees, completed
        lessons, test booking fees, third-party charges (such as RTO fees) and
        discounted or promotional packages are not eligible for refunds, unless
        expressly stated otherwise at the time of purchase.<br></br> 7.5. The
        above is a summary only. All refunds, cancellations, special
        circumstances, force majeure events and the process for requesting a
        refund are governed in full by our Refund Policy. In the event of any
        inconsistency, the Refund Policy shall prevail. For complete details,{" "}
        <a
          href="/refund-policy"
          style={{ color: "#1976d2", textDecoration: "underline" }}
        >
          click here to see more
        </a>
        .<br></br>
        <br></br>
        8. USER VIOLATION OF USER TERMS
        <br></br>
        8.1. You shall not smoke, drink or carry any contraband substances in
        the Vehicles or misbehave with the Driving Instructor or distract the
        Driving Instructor or act in violation of Applicable Law. In the event
        You are found to be involved in the activities set out above, You shall
        be liable to pay a fine to us and we shall also have the right to
        terminate the Lesson. In the event You fail to pay fine after the
        completion of the Lesson, we may at our discretion, take such steps as
        may be available to us under Applicable Law. You shall also be
        blacklisted as a result of non-payment of the fine or misbehaving as the
        case may be, and in such event, Your Account may be terminated by
        InLane.
        <br></br>
        <br></br>
        9. CUSTOMER RELATIONSHIP MANAGEMENT
        <br></br>
        9.1. All issues, opinions, suggestions, questions and feedback while
        availing our Services can be communicated to us via several modes such
        as self-serve app or website or email. After completion of the Lesson,
        you are entitled to give a suitable rating for the service and Lesson.
        You agree to be fair, accurate and non-disparaging while leaving
        comment, feedback, testimonials or reviews on or about the Lessons or
        Services.<br></br> 9.2. Reporting of any issue needs to be within 07
        (seven) days of the happening of the issue, failing which, such issue
        will not be addressed.<br></br> 9.3. Any issue reported on channels
        other than the above may be addressed by InLane only on a best-effort
        basis. InLane takes no liability for inability to get back on other
        channels.<br></br> 9.4. InLane shall endeavour to respond to Your issues
        within 2 (two) working days of Your reporting the same and endeavour to
        resolve it at the earliest possible. It is hereby clarified that issues
        are resolved on a severity basis.
        <br></br>
        <br></br>
        10. FORCE MAJEURE
        <br></br>
        10.1 We shall not be liable for any failure to perform any obligations
        under this User Terms, if the performance is prevented, hindered or
        delayed by a Force Majeure Event and in such case our obligations under
        this User Terms shall be suspended for so long as the Force Majeure
        Event continues.
        <br></br>
        <br></br>
        11. INDEMNIFICATION
        <br></br>
        11.1 By accepting these User Terms and using the Service, You agree that
        You shall defend, indemnify and hold InLane, its affiliates, their
        licensors, and each of its officers, directors, other users, employees,
        attorneys and agents harmless from and against any and all claims,
        costs, damages, losses, liabilities and expenses (including attorneys'
        fees and costs) arising out of or in connection with: (a) Your violation
        or breach of any term of these User Terms or any Applicable Law or
        regulation, whether or not referenced herein; (b) Your violation of any
        rights of any third party, including the TPSPs or (c) Your use or misuse
        of the Application or Service.
        <br></br>
        <br></br>
        12. LIABILITY
        <br></br>
        12.1. The information, recommendations and/or Services provided to You
        on or through the Site, the Application and InLane customer support
        channels are for general information purposes only and do not constitute
        advice. InLane will reasonably keep the Site, and its contents correct
        and up to date but does not guarantee that (the contents of) the Site is
        free of errors, defects, malware and viruses or that the Site is
        correct, up to date and accurate.<br></br> 12.2. InLane shall not be
        liable for You missing trains/flights/events or delays etc. as the
        Service is dependent on many factors not in InLane’s control. You must
        book Your Lesson after taking into account the check-in time, traffic
        and weather conditions, political rallies, natural calamities, traffic
        barricades, car breakdowns and other unexpected delays.<br></br> 12.3.
        In the event, there is a delay by the Vehicle in reaching the pickup
        location beyond 30 (thirty) minutes of the pickup time, InLane shall
        offer a reschedule and the following Lessons will be moved forward.
        <br></br>
        12.4. InLane shall not be liable for any damages resulting from the use
        of or inability to use the Site, including damages caused by wrong usage
        of the Site, error in customer support channels, network issues,
        malware, viruses or any incorrectness or incompleteness of the
        Information on the Platform.<br></br> 12.5. You shall take full
        responsibility of Your items and luggage. In case of lost items inside
        the Vehicle during the journey, InLane will try to locate the items on a
        “best-effort” basis but is not responsible for the same in case of loss
        or damage to the same. If You leave any goods in the Vehicle or have any
        complaint in respect of the Services or the use of the Vehicle, You have
        to inform InLane of the same in writing within 24 (twenty-four) hours of
        using the Vehicle or the Services of InLane.<br></br> 12.6. InLane shall
        not be responsible for any loss of communication / information of status
        update and benefits. All this information will be sent on mobile number
        and/or email ID registered with InLane. InLane will not be responsible
        for appropriateness of mobile or email or any other communication
        medium. You shall be responsible for immediately reporting the errors,
        if any, occurred in the information sent to You regarding booking
        confirmation.<br></br> 12.7. IN NO EVENT SHALL INLANE BE LIABLE FOR ANY
        DIRECT, INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES
        OR FOR ANY DAMAGES WHATSOEVER, WHETHER BASED ON CONTRACT, TORT,
        NEGLIGENCE, STRICT LIABILITY OR OTHERWISE, EVEN IF INLANE HAS BEEN
        ADVISED OF THE POSSIBILITY THEREOF.<br></br> 12.8. IN ADDITION, AND
        WITHOUT LIMITING THE FOREGOING, TO THE FULLEST EXTENT PERMITTED BY
        APPLICABLE LAW, IN NO EVENT WILL INLANE’s AGGREGATE LIABILITY ARISING
        OUT OF OR IN CONNECTION WITH THESE USER TERMS OR THE SERVICES RENDERED
        HEREUNDER, WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE, PRODUCT
        LIABILITY, OR OTHER THEORY), WARRANTY, OR OTHERWISE, EXCEED THE AMOUNT
        OF Rs. 1000/- (Rupees One Thousand only).<br></br> 12.9. If Applicable
        Law does not permit the exclusion of certain warranties or the
        limitation or exclusion of liability, the scope and duration of such
        warranty exclusions and the extent of the liability of InLane shall be
        the minimum permitted under Applicable Law.
        <br></br>
        <br></br>
        13. APPLICATION LICENSE <br></br>13.1. Subject to Your compliance with
        these User Terms, InLane grants You a limited, revocable, non-exclusive,
        non-transferable and non-sub-licensable license to download and install
        a copy of the Application on a single mobile device that You own or
        control and to run such copy of the Application solely for Your own
        personal use and to use the Site.<br></br> 13.2. You shall not (i)
        license, sublicense, sell, resell, transfer, assign, distribute or
        otherwise commercially exploit or make available to any third party the
        Service or Site in any way; (ii) modify or make derivative works based
        upon the Service or Application; (iii) create Internet “links” to the
        Service or “frame” or “mirror” any Site on any other server or wireless
        or Internet-based device; (iv) reverse engineer or access the Site in
        order to (a) design or build a competitive product or service, (b)
        design or build a product using similar ideas, features, functions or
        graphics of the Service or Site, or (c) copy, reproduce, record, or make
        available to the public any ideas, features, functions or graphics of
        the Service or Site, or (v) launch an automated program or script,
        including, but not limited to, web spiders, web crawlers, web robots,
        web scrapers, macro scripts, AI tools/agents, API abusers, DDoS tools,
        web ants, web indexers, bots, viruses or worms, or any program which may
        make multiple server requests per second, or unduly burdens or hinders
        the operation and/or performance of the Service or Site.<br></br> 13.3.
        You shall not: (i) send spam or otherwise duplicative or unsolicited
        messages in violation of applicable laws; (ii) send or store infringing,
        obscene, threatening, libelous, or otherwise unlawful or tortious
        material, including material harmful to children or violative of third
        party privacy rights; (iii) send or store material containing but not
        limited to software viruses, worms, Trojan horses or other harmful
        computer code, files, scripts, agents or programs; (iv) interfere with
        or disrupt the integrity or performance of the Site, the Application or
        Service or the data contained therein; or (v) attempt to gain
        unauthorized access to the Site, the Application or Service or its
        related systems or networks.<br></br> 13.4. InLane will have the right
        to investigate and prosecute violations of any of the above to the
        fullest extent of the law. InLane may involve and cooperate with law
        enforcement authorities in prosecuting users who violate these User
        Terms. You acknowledge that InLane has no obligation to monitor Your
        access to or use of the Site, Service or Posted Content, but has the
        right to do so for the purpose of operating the Site and Service, to
        ensure Your compliance with these User Terms, or to comply with
        Applicable Law or the order or requirement of a court, administrative
        agency or other Governmental body. InLane reserves the right, at any
        time and without prior notice, to remove or disable access to any
        content that InLane, at its sole discretion, considers to be in
        violation of these User Terms or otherwise harmful to the Site, the
        Service or Application.<br></br>
        <br></br> 14. INTELLECTUAL PROPERTY OWNERSHIP <br></br> 14.1. InLane
        alone (and its licensors, where applicable) shall own all right, title
        and interest, including all related intellectual property rights, in and
        to (i) the Site, Application, product, Service and any suggestions,
        ideas, enhancement requests, feedback, recommendations or any other
        offering; (ii) text, graphics, user interfaces, visual interfaces,
        photographs, trademarks, logos, sounds, music, artwork and computer
        code; or (iii) other information provided by You or any other party
        relating to the Site, Application or the Service. Third party trademarks
        may appear on this Site/ Application and all rights therein are reserved
        to the registered owners of those trademarks. For use of any third
        party's intellectual property, You need to get permission directly from
        the owner of the intellectual property for any use.<br></br> 14.2. These
        User Terms do not constitute a sale and do not convey to You any rights
        of ownership in or related to the Site, the Application or the Service,
        or any intellectual property rights owned by InLane. You shall be solely
        responsible for any violations of any laws and for any infringements of
        any intellectual property rights caused by use of the Services or the
        Site/ Application.<br></br> 14.3. You may use information on the Site
        purposely made available by InLane for downloading from the Site,
        provided that You: (i) do not remove any proprietary notice language in
        all copies of such documents and make no modifications to the
        information; (ii) use such information only for Your personal,
        non-commercial informational purpose and do not copy or post such
        information on any networked computer or broadcast it in any media; or
        (iii) do not make any additional representations or warranties relating
        to such information.
        <br></br>
        <br></br>
        15. RESCHEDULE AND NO-SHOW POLICY <br></br> 15.1. Rescheduling Fees: If
        a learner requests to reschedule a driving lesson within 24 hours of the
        scheduled lesson time, a rescheduling fee of INR 300 will apply as per
        the
        <a href="/rescheduling-policy">Reschedule Policy</a>. This fee covers
        administrative costs and compensates for the short notice. Please refer
        to the Reschedule Policy for more information.<br></br> 15.2. No-Show
        Fees: If a learner fails to attend a scheduled lesson and requests to
        reschedule, a nominal fee of INR 300 will be applied as per the{" "}
        <a href="/rescheduling-policy">Reschedule Policy</a>. This fee is in
        addition to any rescheduling fees and compensates for the missed
        appointment and associated inconvenience. Please refer to the Reschedule
        Policy for more information.
        <br></br>
        <br></br>16. LINKS <br></br> 16.1. If permitted by InLane, You may
        establish a hypertext link to the Site, provided that the link does not
        state or imply any sponsorship or endorsement of Your site by Us. You
        must not use on Your site or in any other manner any InLane trademarks
        or service marks or any Content belonging to InLane and appearing on the
        Site, including any logos or characters, without our express written
        consent. You must not frame or otherwise incorporate into another
        third-party website or present in conjunction with or juxtaposed against
        such a website any of the content or other materials on the Site without
        our prior written consent.<br></br>
        <br></br> 17. TERM AND TERMINATION OF LICENSE AGREEMENT <br></br> 17.1.
        Unless terminated explicitly, the agreement between InLane and You is
        perpetual in nture upon downloading the Application and for each Service
        booked through the Site.<br></br> 17.2. You are entitled to terminate
        the agreement at all times by deletion of Your Account, thus disabling
        the use by You of the Site. You can close Your Account at any time by
        following the instructions on the Site.<br></br> 17.3. InLane is
        entitled to terminate the agreement at all times and with immediate
        effect (by disabling Your use of the Site and the Service) if You: (a)
        violate or breach any term of these User Terms, or (b) in the opinion of
        InLane, misuse the Application or the Service. InLane is not obliged to
        give notice of the termination of the agreement in advance. After
        termination InLane will give notice thereof in accordance with these
        User Terms.<br></br> 17.4. Termination of this agreement will not
        prejudice accrued rights of either InLane or You.<br></br> 17.5. All
        provisions which are intended to survive the termination, shall survive
        the expiry/termination of these User Terms in accordance with their
        terms. <br></br>
        <br></br>18. CONFLICT <br></br> 18.1. In the event of any contradiction
        or inconsistency between this User Terms and any other agreement
        executed between You and InLane, the terms of the User Terms shall
        prevail unless the exception has been expressly agreed to in writing by
        making reference to the relevant Clause sought to be modified under this
        User Terms.<br></br>
        <br></br> 19. MODIFICATION OF THE SERVICE AND USER TERMS <br></br> 19.1.
        InLane reserves the right, at its sole discretion, to modify or replace,
        in part or full, any of these User Terms, or change, suspend, block,
        discontinue or restrict your use to any or all features of the Service
        or Application at any time.<br></br> 19.2. InLane shall not be required
        to notify You of any changes made to these User Terms. The revised User
        Terms shall be made available on the Site. You are requested to
        regularly visit the Site to view the most current User Terms. You can
        determine when InLane last modified the User Terms by referring to the
        “Last Updated” at the top of the page. It shall be Your responsibility
        to check these User Terms periodically for changes. InLane may require
        You to provide Your consent to the updated User Terms in a specified
        manner prior to any further use of the Site and the Services. If no such
        separate consent is sought, Your continued use of the Site, following
        the changes to the User Terms, will constitute Your acceptance of those
        changes. Your use of the Site and the Services is subject to the most
        current version of the User Terms made available on the Site at the time
        of such use.<br></br>
        <br></br> 20. NOTICE <br></br> 20.1. InLane may give notice by means of
        a general notice on the Service or Application, or by electronic mail to
        Your registered email address or a message on Your registered mobile
        number, or by written communication sent by regular mail to Your address
        on record in InLane’s account information.<br></br> 20.2. In case any
        query or complaint is unresolved or if you did not receive a
        satisfactory response from the 24*7 support, you can escalate the matter
        to our Grievance Oﬃce by sharing the details of the complaint ticket
        created: Details of the Grievance Office (+91 73380 98798)<br></br>
        <br></br> 21. ASSIGNMENT<br></br> 21.1. You shall not assign Your rights
        under these User Terms without prior written approval of InLane. InLane
        can assign its rights under the User Terms to any affiliate.<br></br>
        <br></br> 22. APPLICABLE LAW AND DISPUTE RESOLUTION <br></br>These User
        Terms are subject to the laws of India. Any dispute, claim or
        controversy arising out of or relating to these User Terms or the
        breach, termination, enforcement, interpretation or validity thereof or
        the use of the Site, the Service or the Application (collectively,
        “Disputes”) the parties shall attempt to settle the same amicably,
        through negotiation and consultation at such offices of InLane as InLane
        may designate. In the event, the dispute is not resolved internally
        between You and InLane after at least 30 (thirty) days of negotiation,
        in good faith, the same shall be subject to binding and final
        arbitration in accordance with the Arbitration and Conciliation Act,
        1996 as amended from time to time or in case the Arbitration and
        Conciliation Act, 1996 is no longer in force, as per any law relating to
        arbitration in force at the time of such reference. The reference shall
        be made to a sole arbitrator mutually appointed by InLane and You. The
        place of the arbitration shall be Kolkata, West Bengal, unless otherwise
        mutually agreed by InLane and You in writing. Subject to the above, any
        Dispute will be subject to the exclusive jurisdiction of courts in
        Kolkata, India.
      </Typography>
    </PageTemplate>
  );
};

export default TermsAndConditions;
